<?php

namespace Sofitech\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findAllMainCategories(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM SofitechAdminBundle:Category p WHERE p.parentCategory IS NULL'
            )
            ->getResult();
    }
}
