sofitech_admin:
    resource: "@SofitechAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@SofitechAdminBundle/Controller/"
    type: "annotation"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    type: "xml"


