sofitech_admin:
    resource: "@SofitechAdminBundle/Resources/config/routing.yml"
    prefix:   /

student:
    resource: "@SofitechAdminBundle/Controller/StudentController.php"
    type: "annotation"

adress:
    resource: "@SofitechAdminBundle/Controller/AdressController.php"
    type: "annotation"

company:
    resource: "@SofitechAdminBundle/Controller/CompanyController.php"
    type: "annotation"

