sofitech_admin:
    resource: "@SofitechAdminBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@SofitechAdminBundle/Controller/"
    type: "annotation"

formation:
    resource: "@SofitechAdminBundle/Controller/FormationController.php"
    type: "annotation"

